set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TOOLCHAIN_ROOT_DEFAULT "/opt/homebrew/opt/aarch64-unknown-linux-gnu/toolchain")
set(AARCH64_LINUX_GNU_TOOLCHAIN_ROOT "${TOOLCHAIN_ROOT_DEFAULT}" CACHE PATH "Root path of the aarch64 Linux GNU toolchain")
set(LLVM_ROOT_DEFAULT "/opt/homebrew/opt/llvm")
set(HOMEBREW_LLVM_ROOT "${LLVM_ROOT_DEFAULT}" CACHE PATH "Root path of the Homebrew LLVM toolchain")

set(CMAKE_C_COMPILER "${HOMEBREW_LLVM_ROOT}/bin/clang")
set(CMAKE_CXX_COMPILER "${HOMEBREW_LLVM_ROOT}/bin/clang++")

set(CMAKE_C_COMPILER_TARGET aarch64-unknown-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET aarch64-unknown-linux-gnu)

set(CMAKE_SYSROOT "${AARCH64_LINUX_GNU_TOOLCHAIN_ROOT}/aarch64-unknown-linux-gnu/sysroot")
set(CMAKE_C_FLAGS_INIT "--gcc-toolchain=${AARCH64_LINUX_GNU_TOOLCHAIN_ROOT} --sysroot=${CMAKE_SYSROOT}")
set(CMAKE_CXX_FLAGS_INIT "--gcc-toolchain=${AARCH64_LINUX_GNU_TOOLCHAIN_ROOT} --sysroot=${CMAKE_SYSROOT}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "--gcc-toolchain=${AARCH64_LINUX_GNU_TOOLCHAIN_ROOT} --sysroot=${CMAKE_SYSROOT}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "--gcc-toolchain=${AARCH64_LINUX_GNU_TOOLCHAIN_ROOT} --sysroot=${CMAKE_SYSROOT}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "--gcc-toolchain=${AARCH64_LINUX_GNU_TOOLCHAIN_ROOT} --sysroot=${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH
    "${CMAKE_SYSROOT}"
    "${AARCH64_LINUX_GNU_TOOLCHAIN_ROOT}/aarch64-unknown-linux-gnu"
    "${AARCH64_LINUX_GNU_TOOLCHAIN_ROOT}"
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
