POSITIONAL_ATTRS_MAP: dict[str, dict[int, str]] = {
    "operator.getitem": {1: "index"},
    "<built-in function getitem>": {1: "index"},
    "aten.add.Tensor": {1: "other", 2: "alpha"},
    "aten.add.Scalar": {1: "other", 2: "alpha"},
    "aten.sub.Tensor": {1: "other", 2: "alpha"},
    "aten.sub.Scalar": {1: "other", 2: "alpha"},
    "aten.mul.Tensor": {1: "other"},
    "aten.mul.Scalar": {1: "other"},
    "aten.div.Tensor": {1: "other"},
    "aten.div.Scalar": {1: "other"},
    "aten.div.Tensor_mode": {1: "other", 2: "rounding_mode"},
    "aten.floor_divide.default": {1: "other"},
    "aten.eq.Tensor": {1: "other"},
    "aten.eq.Scalar": {1: "other"},
    "aten.ne.Tensor": {1: "other"},
    "aten.ne.Scalar": {1: "other"},
    "aten.lt.Tensor": {1: "other"},
    "aten.lt.Scalar": {1: "other"},
    "aten.gt.Tensor": {1: "other"},
    "aten.gt.Scalar": {1: "other"},
    "aten.le.Tensor": {1: "other"},
    "aten.le.Scalar": {1: "other"},
    "aten.ge.Tensor": {1: "other"},
    "aten.ge.Scalar": {1: "other"},
    "aten.bitwise_or.Tensor": {1: "other"},
    "aten.bitwise_and.Tensor": {1: "other"},
    "aten.pow.Tensor_Scalar": {1: "exponent"},
    "aten.pow.Tensor_Tensor": {1: "exponent"},
    "aten.pow.Scalar": {1: "exponent"},
    "aten.mean.dim": {1: "dim", 2: "keepdim"},
    "aten.sum.dim_IntList": {1: "dim", 2: "keepdim", 3: "dtype"},
    "aten.var.dim": {1: "dim", 2: "correction", 3: "keepdim"},
    "aten.var.correction": {1: "dim", 2: "correction", 3: "keepdim"},
    "aten.max.dim": {1: "dim", 2: "keepdim"},
    "aten.amax.default": {1: "dim", 2: "keepdim"},
    "aten.min.dim": {1: "dim", 2: "keepdim"},
    "aten.amin.default": {1: "dim", 2: "keepdim"},
    "aten.any.dim": {1: "dim", 2: "keepdim"},
    "aten.softmax.int": {1: "dim", 2: "dtype"},
    "aten._softmax.default": {1: "dim", 2: "half_to_float"},
    "aten.topk.default": {1: "k", 2: "dim", 3: "largest", 4: "sorted"},
    "aten.sort.default": {1: "dim", 2: "descending"},
    "aten.view.default": {1: "shape"},
    "aten.reshape.default": {1: "shape"},
    "aten.flatten.using_ints": {1: "start_dim", 2: "end_dim"},
    "aten.unfold.default": {1: "dim", 2: "size", 3: "step"},
    "aten.unsqueeze.default": {1: "dim"},
    "aten.expand.default": {1: "shape", 2: "implicit"},
    "aten.t.default": {},
    "aten.transpose.int": {1: "dim0", 2: "dim1"},
    "aten.permute.default": {1: "permutation"},
    "aten.slice.Tensor": {1: "dim", 2: "start", 3: "end", 4: "step"},
    "aten.select.int": {1: "dim", 2: "index"},
    "aten.narrow.default": {1: "dim", 2: "start", 3: "length"},
    "aten.index.Tensor": {1: "indices"},
    "aten.index_put.default": {3: "accumulate"},
    "aten.constant_pad_nd.default": {1: "pad", 2: "value"},
    "aten.cat.default": {1: "dim"},
    "aten.embedding.default": {2: "padding_idx", 3: "scale_grad_by_freq", 4: "sparse"},
    "aten.gather.default": {1: "dim", 2: "index"},
    "aten.split_with_sizes.default": {1: "split_sizes", 2: "dim"},
    "aten.scatter.src": {1: "dim", 2: "index"},
    "aten.scatter.value": {1: "dim", 2: "index", 3: "value"},
    "aten.scatter_reduce.two": {1: "dim", 2: "index", 4: "reduce", 5: "include_self"},
    "aten.histc.default": {1: "bins", 2: "min", 3: "max"},
    "aten.cumsum.default": {1: "dim", 2: "dtype"},
    "aten.empty_permuted.default": {0: "size", 1: "stride"},
    "aten.clamp.default": {1: "min", 2: "max"},
    "aten.clamp.Tensor": {1: "min", 2: "max"},
    "aten.gelu.default": {1: "approximate"},
    "aten.convolution.default": {
        3: "stride",
        4: "padding",
        5: "dilation",
        6: "transposed",
        7: "output_padding",
        8: "groups",
    },
    "aten.conv1d.default": {3: "stride", 4: "padding", 5: "dilation", 6: "groups"},
    "aten.conv2d.default": {3: "stride", 4: "padding", 5: "dilation", 6: "groups"},
    "aten.upsample_nearest2d.default": {1: "output_size", 2: "scales_h", 3: "scales_w"},
    "aten.upsample_nearest2d.vec": {1: "output_size", 2: "scale_factors"},
    "aten.native_group_norm.default": {3: "batch_size", 4: "channels", 5: "height_width", 6: "num_groups", 7: "eps"},
    "aten.group_norm.default": {1: "num_groups", 4: "eps"},
    "aten.native_batch_norm.default": {5: "training", 6: "momentum", 7: "eps"},
    "aten.batch_norm.default": {5: "training", 6: "momentum", 7: "eps", 8: "cudnn_enabled"},
    "aten.native_layer_norm.default": {1: "normalized_shape", 4: "eps"},
    "aten.layer_norm.default": {1: "normalized_shape", 4: "eps"},
    "aten.scaled_dot_product_attention.default": {
        3: "attn_mask",
        4: "dropout_p",
        5: "is_causal",
        6: "scale",
        7: "enable_gqa",
    },
    "aten.arange.default": {0: "end"},
    "aten.arange.start": {0: "start", 1: "end"},
    "aten.arange.start_step": {0: "start", 1: "end", 2: "step"},
    "aten.full.default": {0: "size", 1: "fill_value"},
    "aten.full_like.default": {1: "fill_value"},
    "aten.stft.default": {
        1: "n_fft",
        2: "hop_length",
        3: "win_length",
        5: "normalized",
        6: "onesided",
        7: "return_complex",
    },
    "aten.fft_rfft.default": {1: "n", 2: "dim", 3: "norm"},
    "aten.fft_irfft.default": {1: "n", 2: "dim", 3: "norm"},
}
