LAYER_ATTRS_MAP = {
    "aten._assert_tensor_metadata.default": ["size", "stride", "dtype"],
    "aten._softmax.default": ["dim", "half_to_float"],
    "aten._to_copy.default": [],
    "aten.add.Tensor": ["scalar"],
    "aten.arange.start_step": ["start", "end", "step"],
    "aten.bitwise_and.Tensor": [],
    "aten.bitwise_or.Tensor": [],
    "aten.bmm.default": [],
    "aten.cat.default": ["dim"],
    "aten.clone.default": [],
    "aten.cos.default": [],
    "aten.cumsum.default": ["dim"],
    "aten.div.Tensor": ["scalar"],
    "aten.embedding.default": ["padding_idx"],
    "aten.eq.Scalar": ["scalar"],
    "aten.eq.Tensor": [],
    "aten.expand.default": ["shape"],
    "aten.full.default": ["shape", "fill_value"],
    "aten.gelu.default": [],
    "aten.gt.Tensor": [],
    "aten.index.Tensor": [],
    "aten.index_put.default": [],
    "aten.le.Tensor": [],
    "aten.mean.dim": ["dim", "keepdim"],
    "aten.mm.default": [],
    "aten.mul.Tensor": ["scalar"],
    "aten.ne.Scalar": ["scalar"],
    "aten.neg.default": [],
    "aten.permute.default": ["dims"],
    "aten.pow.Tensor_Scalar": ["exponent"],
    "aten.scalar_tensor.default": ["value"],
    "aten.select.int": ["dim", "index"],
    "aten.sin.default": [],
    "aten.slice.Tensor": ["dim", "start", "end", "step"],
    "aten.sub.Tensor": ["scalar"],
    "aten.tanh.default": [],
    "aten.unsqueeze.default": ["dim"],
    "aten.view.default": ["shape"],
    "aten.where.self": [],
}

#Dictates maximum DFS depth during fusion search
DFS_DEPTH = 10
