LAYER_ATTRS_MAP = {
    "aten._assert_tensor_metadata.default": ["size", "stride", "dtype"],
    "aten._softmax.default": ["dim", "half_to_float"],
    "aten._to_copy.default": [None, "dtype", "layout", "device", "pin_memory", "non_blocking", "memory_format"],
    "aten.add.Scalar": ["scalar"],
    "aten.add.Tensor": ["scalar"],
    "aten.addmm.default": [None, None, None, "beta", "alpha"],
    "aten.arange.start_step": ["start", "end", "step"],
    "aten.avg_pool1d.default": [None, "kernel_size", "stride", "padding", "ceil_mode", "count_include_pad"],
    "aten.avg_pool2d.default": [None, "kernel_size", "stride", "padding", "ceil_mode", "count_include_pad", "divisor_override"],
    "aten.batch_norm.default": [None, None, None, None, None, "training", "momentum", "eps", "cudnn_enabled"],
    "aten.bitwise_and.Tensor": [],
    "aten.bitwise_or.Tensor": [],
    "aten.bmm.default": [],
    "aten.cat.default": ["dim"],
    "aten.clone.default": [],
    "aten.clamp.default": [None, "min", "max"],
    "aten.clamp_max.default": [None, "max"],
    "aten.clamp_min.default": [None, "min"],
    "aten.convolution.default": [None, None, None, "stride", "padding", "dilation", "transposed", "output_padding", "groups"],
    "aten.conv1d.default": [None, None, None, "stride", "padding", "dilation", "groups"],
    "aten.conv2d.default": [None, None, None, "stride", "padding", "dilation", "groups"],
    "aten.cos.default": [],
    "aten.cumsum.default": ["dim"],
    "aten.div.Scalar": ["scalar"],
    "aten.div.Tensor": ["scalar"],
    "aten.embedding.default": ["padding_idx"],
    "aten.eq.Scalar": ["scalar"],
    "aten.eq.Tensor": [],
    "aten.expand.default": ["shape"],
    "aten.full.default": ["shape", "fill_value"],
    "aten.gelu.default": [],
    "aten.glu.default": ["dim"],
    "aten.group_norm.default": [None, "num_groups", None, None, "eps", "cudnn_enabled"],
    "aten.gt.Tensor": [],
    "aten.index.Tensor": [],
    "aten.index_put.default": [],
    "aten.layer_norm.default": [None, "normalized_shape", None, None, "eps", "cudnn_enabled"],
    "aten.le.Tensor": [],
    "aten.linear.default": [],
    "aten.max.dim": ["dim", "keepdim"],
    "aten.max_pool1d.default": [None, "kernel_size", "stride", "padding", "dilation", "ceil_mode"],
    "aten.max_pool2d.default": [None, "kernel_size", "stride", "padding", "dilation", "ceil_mode"],
    "aten.mean.dim": ["dim", "keepdim"],
    "aten.mm.default": [],
    "aten.mul.Scalar": ["scalar"],
    "aten.mul.Tensor": ["scalar"],
    "aten.native_batch_norm.default": [None, None, None, None, None, "training", "momentum", "eps"],
    "aten.native_layer_norm.default": [None, "normalized_shape", None, None, "eps"],
    "aten.ne.Scalar": ["scalar"],
    "aten.ne.Tensor": [],
    "aten.neg.default": [],
    "aten.permute.default": ["dims"],
    "aten.pow.Tensor_Scalar": ["exponent"],
    "aten.rms_norm.default": [None, "normalized_shape", None, "eps"],
    "aten.scalar_tensor.default": ["value"],
    "aten.scaled_dot_product_attention.default": [None, None, None, "attn_mask", "dropout_p", "is_causal", "scale", "enable_gqa"],
    "aten.select.int": ["dim", "index"],
    "aten.sin.default": [],
    "aten.slice.Tensor": ["dim", "start", "end", "step"],
    "aten.sub.Scalar": ["scalar"],
    "aten.sub.Tensor": ["scalar"],
    "aten.sum.dim_IntList": ["dim", "keepdim"],
    "aten.tanh.default": [],
    "aten.topk.default": [None, "k", "dim", "largest", "sorted"],
    "aten.transpose.int": ["dim0", "dim1"],
    "aten.unsqueeze.default": ["dim"],
    "aten.var.dim": ["dim", "unbiased", "keepdim"],
    "aten.view.default": ["shape"],
    "aten.where.self": [],
}

#Dictates maximum DFS depth during fusion search
DFS_DEPTH = 10
