from . import models as M

EXPERT_GROUP = "experts"

def _edge(
    source: str,
    dest: str,
    dest_input_index: int | None = 0,
    *,
    repeated: bool = False,
    repeated_group: str | None = None,
) -> M.FusionEdge:
    return M.FusionEdge(
        source=source,
        dest=dest,
        dest_input_index=dest_input_index,
        repeated=repeated,
        repeated_group=repeated_group,
    )

def _expert_edge(
    source: str,
    dest: str,
    dest_input_index: int | None = 0,
) -> M.FusionEdge:
    return _edge(
        source,
        dest,
        dest_input_index,
        repeated=True,
        repeated_group=EXPERT_GROUP,
    )

EDGES: dict[str, M.FusionEdge] = {
    "linear_mm_to_bias_add": _edge("linear_mm", "linear_bias_add", 0),
    "linear_weight_transpose_to_mm": _edge("linear_weight_transpose", "linear_mm", 1),
    "linear_weight_transpose_to_addmm": _edge("linear_weight_transpose", "linear_addmm", 2),
    "rms_square_to_mean": _edge("rms_square", "rms_mean", 0),
    "rms_mean_to_eps_add": _edge("rms_mean", "rms_eps_add", 0),
    "rms_eps_add_to_inv": _edge("rms_eps_add", "rms_inv", 0),
    "rms_eps_add_to_inv_pow": _edge("rms_eps_add", "rms_inv_pow", 0),
    "rms_inv_to_scale": _edge("rms_inv", "rms_scale", 1),
    "rms_inv_pow_to_scale": _edge("rms_inv_pow", "rms_scale", 1),
    "rms_scale_to_weight_mul": _edge("rms_scale", "rms_weight_mul", 0),
    "rms_scale_to_precision_cast": _edge("rms_scale", "precision_cast", 0),
    "rms_precision_cast_to_weight_mul": _edge("precision_cast", "rms_weight_mul", 1),
    "ln_mean_to_center": _edge("ln_mean", "ln_center", 1),
    "ln_center_to_square": _edge("ln_center", "ln_square", 0),
    "ln_square_to_var": _edge("ln_square", "ln_var", 0),
    "ln_var_to_eps_add": _edge("ln_var", "ln_eps_add", 0),
    "ln_eps_add_to_inv": _edge("ln_eps_add", "ln_inv", 0),
    "ln_center_to_norm": _edge("ln_center", "ln_norm", 0),
    "ln_inv_to_norm": _edge("ln_inv", "ln_norm", 1),
    "ln_norm_to_weight_mul": _edge("ln_norm", "ln_weight_mul", 0),
    "ln_weight_mul_to_bias_add": _edge("ln_weight_mul", "ln_bias_add", 0),
    "gate_proj_to_activation": _edge("gate_proj", "mlp_activation", 0),
    "mlp_activation_to_product": _edge("mlp_activation", "mlp_product", 0),
    "up_proj_to_product": _edge("up_proj", "mlp_product", 1),
    "mlp_product_to_down_proj": _edge("mlp_product", "down_proj", 0),
    "gate_input_view_to_gate_proj": _edge("gate_input_view", "gate_proj", 0),
    "gate_weight_transpose_to_gate_proj": _edge("gate_weight_transpose", "gate_proj", 1),
    "gate_proj_to_gate_proj_view": _edge("gate_proj", "gate_proj_view", 0),
    "gate_proj_view_to_gelu": _edge("gate_proj_view", "gelu", 0),
    "gelu_to_product": _edge("gelu", "mlp_product", 0),
    "up_input_view_to_up_proj": _edge("up_input_view", "up_proj", 0),
    "up_weight_transpose_to_up_proj": _edge("up_weight_transpose", "up_proj", 1),
    "up_proj_to_up_proj_view": _edge("up_proj", "up_proj_view", 0),
    "up_proj_view_to_product": _edge("up_proj_view", "mlp_product", 1),
    "mlp_product_to_product_view": _edge("mlp_product", "mlp_product_view", 0),
    "product_view_to_down_proj": _edge("mlp_product_view", "down_proj", 0),
    "down_weight_transpose_to_down_proj": _edge("down_weight_transpose", "down_proj", 1),
    "down_proj_to_down_proj_view": _edge("down_proj", "down_proj_view", 0),
    "up_proj_to_gelu": _edge("up_proj", "gelu", 0),
    "gelu_to_down_proj": _edge("gelu", "down_proj", 0),
    "attn_qk_to_scale": _edge("attn_qk", "attn_scale", 0),
    "attn_scale_to_mask_add": _edge("attn_scale", "attn_mask_add", 0),
    "attn_scale_to_softmax": _edge("attn_scale", "attn_softmax", 0),
    "attn_mask_add_to_softmax": _edge("attn_mask_add", "attn_softmax", 0),
    "attn_softmax_to_value": _edge("attn_softmax", "attn_value", 0),
    "lfm_attn_query_expand_to_flat": _edge("lfm_attn_query_expand", "lfm_attn_query_flat", 0),
    "lfm_attn_key_expand_to_flat": _edge("lfm_attn_key_expand", "lfm_attn_key_flat", 0),
    "lfm_attn_value_expand_to_flat": _edge("lfm_attn_value_expand", "lfm_attn_value_flat", 0),
    "lfm_attn_query_flat_to_qk": _edge("lfm_attn_query_flat", "lfm_attn_qk", 0),
    "lfm_attn_key_flat_to_qk": _edge("lfm_attn_key_flat", "lfm_attn_qk", 1),
    "lfm_attn_qk_to_logits_view": _edge("lfm_attn_qk", "lfm_attn_logits_view", 0),
    "lfm_attn_logits_view_to_mask_add": _edge("lfm_attn_logits_view", "lfm_attn_mask_add", 0),
    "lfm_attn_mask_where_to_add": _edge("lfm_attn_mask_where", "lfm_attn_mask_add", 1),
    "lfm_attn_mask_zero_to_where": _edge("lfm_attn_mask_zero", "lfm_attn_mask_where", 1),
    "lfm_attn_mask_fill_to_where": _edge("lfm_attn_mask_fill", "lfm_attn_mask_where", 2),
    "lfm_attn_mask_add_to_softmax": _edge("lfm_attn_mask_add", "lfm_attn_softmax", 0),
    "lfm_attn_mask_add_to_null_eq": _edge("lfm_attn_mask_add", "lfm_attn_null_eq", 0),
    "lfm_attn_null_eq_to_valid_not": _edge("lfm_attn_null_eq", "lfm_attn_valid_not", 0),
    "lfm_attn_valid_not_to_any": _edge("lfm_attn_valid_not", "lfm_attn_any_valid", 0),
    "lfm_attn_any_to_invalid_not": _edge("lfm_attn_any_valid", "lfm_attn_invalid_not", 0),
    "lfm_attn_invalid_not_to_probs_where": _edge("lfm_attn_invalid_not", "lfm_attn_probs_where", 0),
    "lfm_attn_softmax_to_zero_like": _edge("lfm_attn_softmax", "lfm_attn_zero_like", 0),
    "lfm_attn_zero_like_to_probs_where": _edge("lfm_attn_zero_like", "lfm_attn_probs_where", 1),
    "lfm_attn_softmax_to_probs_where": _edge("lfm_attn_softmax", "lfm_attn_probs_where", 2),
    "lfm_attn_probs_where_to_expand": _edge("lfm_attn_probs_where", "lfm_attn_probs_expand", 0),
    "lfm_attn_probs_expand_to_flat": _edge("lfm_attn_probs_expand", "lfm_attn_probs_flat", 0),
    "lfm_attn_probs_flat_to_output_bmm": _edge("lfm_attn_probs_flat", "lfm_attn_output_bmm", 0),
    "lfm_attn_value_flat_to_output_bmm": _edge("lfm_attn_value_flat", "lfm_attn_output_bmm", 1),
    "lfm_attn_output_bmm_to_view": _edge("lfm_attn_output_bmm", "lfm_attn_output_view", 0),
    "rope_slice_odd_to_neg": _edge("rope_slice_odd", "rope_neg", 0),
    "rope_neg_to_rotate_cat": _edge("rope_neg", "rope_rotate_cat", 0),
    "rope_slice_even_to_rotate_cat": _edge("rope_slice_even", "rope_rotate_cat", 1),
    "rope_cos_mul_to_add": _edge("rope_cos_mul", "rope_add", 0),
    "rope_sin_mul_to_add": _edge("rope_sin_mul", "rope_add", 1),
    "rope_rotate_cat_to_sin_mul": _edge("rope_rotate_cat", "rope_sin_mul", 0),
    "conv_to_bias_add": _edge("conv", "conv_bias_add", 0),
    "conv_to_slice": _edge("conv", "slice", 0),
    "multiply_to_sum": _edge("multiply", "sum", 0),
    "lstm_gate_mm_to_add": _edge("lstm_gate_mm", "lstm_gate_add", 0),
    "lstm_recurrent_mm_to_add": _edge("lstm_recurrent_mm", "lstm_gate_add", 1),
    "lstm_add_to_sigmoid": _edge("lstm_gate_add", "lstm_sigmoid", 0),
    "lstm_add_to_tanh": _edge("lstm_gate_add", "lstm_tanh", 0),
    "lfm_conv_cache_clone_to_output_copy": _edge("lfm_conv_cache_clone", "lfm_conv_cache_output_copy", 0),
    "lfm_conv_cache_scatter_dim0_to_output_copy": _edge("lfm_conv_cache_scatter_dim0", "lfm_conv_cache_output_copy", 1),
    "lfm_conv_cache_clone_to_gather": _edge("lfm_conv_cache_clone", "lfm_conv_cache_gather", 0),
    "lfm_conv_cache_roll_mod_to_gather": _edge("lfm_conv_cache_roll_mod", "lfm_conv_cache_gather", 1),
    "lfm_conv_cache_roll_add_to_mod": _edge("lfm_conv_cache_roll_add", "lfm_conv_cache_roll_mod", 0),
    "lfm_conv_cache_roll_arange_to_add": _edge("lfm_conv_cache_roll_arange", "lfm_conv_cache_roll_add", 0),
    "lfm_conv_cache_gather_to_scatter_dim0": _edge("lfm_conv_cache_gather", "lfm_conv_cache_scatter_dim0", 0),
    "lfm_conv_cache_scatter_dim1_to_scatter_dim0": _edge("lfm_conv_cache_scatter_dim1", "lfm_conv_cache_scatter_dim0", 1),
    "lfm_conv_cache_scatter_slice_dim0_to_scatter_dim1": _edge("lfm_conv_cache_scatter_slice_dim0", "lfm_conv_cache_scatter_dim1", 0),
    "lfm_conv_cache_scatter_dim2_to_scatter_dim1": _edge("lfm_conv_cache_scatter_dim2", "lfm_conv_cache_scatter_dim1", 1),
    "lfm_conv_cache_scatter_slice_dim1_to_scatter_dim2": _edge("lfm_conv_cache_scatter_slice_dim1", "lfm_conv_cache_scatter_dim2", 0),
    "lfm_conv_cache_value_copy_to_scatter_dim2": _edge("lfm_conv_cache_value_copy", "lfm_conv_cache_scatter_dim2", 1),
    "lfm_conv_cache_gather_to_scatter_slice_dim0": _edge("lfm_conv_cache_gather", "lfm_conv_cache_scatter_slice_dim0", 0),
    "lfm_conv_cache_scatter_slice_dim0_to_scatter_slice_dim1": _edge("lfm_conv_cache_scatter_slice_dim0", "lfm_conv_cache_scatter_slice_dim1", 0),
    "lfm_conv_cache_gather_to_value_slice_dim0": _edge("lfm_conv_cache_gather", "lfm_conv_cache_value_slice_dim0", 0),
    "lfm_conv_cache_value_slice_dim0_to_value_slice_dim1": _edge("lfm_conv_cache_value_slice_dim0", "lfm_conv_cache_value_slice_dim1", 0),
    "lfm_conv_cache_value_slice_dim1_to_value_slice_last": _edge("lfm_conv_cache_value_slice_dim1", "lfm_conv_cache_value_slice_last", 0),
    "lfm_conv_cache_value_slice_last_to_value_copy": _edge("lfm_conv_cache_value_slice_last", "lfm_conv_cache_value_copy", 0),
    "moe_hidden_to_router": _edge("moe_hidden_view", "moe_router_logits", 0),
    "moe_router_weight_to_router": _edge("moe_router_weight_transpose", "moe_router_logits", 1),
    "moe_router_logits_to_sigmoid": _edge("moe_router_logits", "moe_router_sigmoid", 0),
    "moe_router_sigmoid_to_bias": _edge("moe_router_sigmoid", "moe_router_bias", 0),
    "moe_router_bias_to_topk": _edge("moe_router_bias", "moe_topk", 0),
    "moe_topk_to_indices": _edge("moe_topk", "moe_topk_indices", 0),
    "moe_router_sigmoid_to_gather": _edge("moe_router_sigmoid", "moe_routing_gather", 0),
    "moe_topk_indices_to_gather": _edge("moe_topk_indices", "moe_routing_gather", 1),
    "moe_gather_to_routing_sum": _edge("moe_routing_gather", "moe_routing_sum", 0),
    "moe_routing_sum_to_eps": _edge("moe_routing_sum", "moe_routing_eps", 0),
    "moe_gather_to_norm": _edge("moe_routing_gather", "moe_routing_norm", 0),
    "moe_eps_to_norm": _edge("moe_routing_eps", "moe_routing_norm", 1),
    "moe_norm_to_scale": _edge("moe_routing_norm", "moe_routing_scale", 0),
    "moe_token_arange_to_unsqueeze": _edge("moe_token_arange", "moe_token_unsqueeze", 0),
    "moe_token_unsqueeze_to_expand": _edge("moe_token_unsqueeze", "moe_token_expand", 0),
    "moe_token_expand_to_clone": _edge("moe_token_expand", "moe_token_clone", 0),
    "moe_token_clone_to_flat": _edge("moe_token_clone", "moe_token_flat", 0),
    "moe_token_expand_to_flat": _edge("moe_token_expand", "moe_token_flat", 0),
    "moe_scale_to_routing_flat": _edge("moe_routing_scale", "moe_routing_flat", 0),
    "moe_topk_indices_to_flat": _edge("moe_topk_indices", "moe_topk_flat", 0),
    "moe_topk_flat_to_sort": _edge("moe_topk_flat", "moe_sort", 0),
    "moe_sort_to_indices": _edge("moe_sort", "moe_sort_indices", 0),
    "moe_unsort_empty_to_index_put": _edge("moe_unsort_empty", "moe_unsort_index_put", 0),
    "moe_sort_indices_to_index_put": _edge("moe_sort_indices", "moe_unsort_index_put", 1),
    "moe_unsort_arange_to_index_put": _edge("moe_unsort_arange", "moe_unsort_index_put", 2),
    "moe_topk_flat_to_sorted_expert_index": _edge("moe_topk_flat", "moe_sorted_expert_index", 0),
    "moe_sort_indices_to_sorted_expert_index": _edge("moe_sort_indices", "moe_sorted_expert_index", 1),
    "moe_sorted_expert_index_to_copy": _edge("moe_sorted_expert_index", "moe_sorted_expert_copy", 0),
    "moe_sorted_expert_copy_to_histc": _edge("moe_sorted_expert_copy", "moe_histc", 0),
    "moe_histc_to_offsets": _edge("moe_histc", "moe_offsets", 0),
    "moe_routing_flat_to_sorted_routing_index": _edge("moe_routing_flat", "moe_sorted_routing_index", 0),
    "moe_sort_indices_to_sorted_routing_index": _edge("moe_sort_indices", "moe_sorted_routing_index", 1),
    "moe_token_flat_to_positions_index": _edge("moe_token_flat", "moe_token_positions_index", 0),
    "moe_sort_indices_to_positions_index": _edge("moe_sort_indices", "moe_token_positions_index", 1),
    "moe_hidden_to_sorted_hidden_index": _edge("moe_hidden_view", "moe_sorted_hidden_index", 0),
    "moe_positions_to_sorted_hidden_index": _edge("moe_token_positions_index", "moe_sorted_hidden_index", 1),
    "moe_gate_up_weight_to_grouped": _edge("moe_gate_up_weight_transpose", "moe_grouped_gate_up", 1),
    "moe_sorted_hidden_to_grouped_gate_up": _edge("moe_sorted_hidden_index", "moe_grouped_gate_up", 0),
    "moe_offsets_to_grouped_gate_up": _edge("moe_offsets", "moe_grouped_gate_up", 2),
    "moe_grouped_gate_up_to_split": _edge("moe_grouped_gate_up", "moe_gate_up_split", 0),
    "moe_split_to_gate": _edge("moe_gate_up_split", "moe_gate_tensor", 0),
    "moe_split_to_up": _edge("moe_gate_up_split", "moe_up_tensor", 0),
    "moe_gate_to_copy": _edge("moe_gate_tensor", "moe_gate_copy", 0),
    "moe_gate_copy_to_sigmoid": _edge("moe_gate_copy", "moe_gate_sigmoid", 0),
    "moe_gate_copy_to_activation": _edge("moe_gate_copy", "moe_gate_activation", 0),
    "moe_gate_sigmoid_to_activation": _edge("moe_gate_sigmoid", "moe_gate_activation", 1),
    "moe_gate_activation_to_copy": _edge("moe_gate_activation", "moe_gate_activation_copy", 0),
    "moe_gate_copy_to_silu": _edge("moe_gate_copy", "moe_gate_silu", 0),
    "moe_gate_silu_to_copy": _edge("moe_gate_silu", "moe_gate_activation_copy", 0),
    "moe_gate_activation_copy_to_product": _edge("moe_gate_activation_copy", "moe_expert_product", 0),
    "moe_up_to_product": _edge("moe_up_tensor", "moe_expert_product", 1),
    "moe_product_to_grouped_down": _edge("moe_expert_product", "moe_grouped_down", 0),
    "moe_down_weight_to_grouped": _edge("moe_down_weight_transpose", "moe_grouped_down", 1),
    "moe_offsets_to_grouped_down": _edge("moe_offsets", "moe_grouped_down", 2),
    "moe_sorted_routing_to_unsqueeze": _edge("moe_sorted_routing_index", "moe_routing_unsqueeze", 0),
    "moe_grouped_down_to_weighted": _edge("moe_grouped_down", "moe_grouped_weighted", 0),
    "moe_routing_unsqueeze_to_weighted": _edge("moe_routing_unsqueeze", "moe_grouped_weighted", 1),
    "moe_weighted_to_unsort_index": _edge("moe_grouped_weighted", "moe_unsort_index", 0),
    "moe_unsort_index_put_to_unsort_index": _edge("moe_unsort_index_put", "moe_unsort_index", 1),
    "moe_unsort_index_to_output_view": _edge("moe_unsort_index", "moe_output_view", 0),
    "moe_output_view_to_combine": _edge("moe_output_view", "moe_grouped_combine", 0),
    "expert_gate_to_activation": _expert_edge("expert_gate", "expert_activation", 0),
    "expert_activation_to_product": _expert_edge("expert_activation", "expert_product", 0),
    "expert_up_to_product": _expert_edge("expert_up", "expert_product", 1),
    "expert_product_to_down": _expert_edge("expert_product", "expert_down", 0),
    "expert_down_to_weighted": _expert_edge("expert_down", "expert_weighted", 0),
    "sample_topk_to_softmax": _edge("sample_topk", "sample_softmax", 0),
    "silu_sigmoid_to_product": _edge("silu_sigmoid", "silu_product", 1),
    "glu_left_slice_to_product": _edge("glu_left_slice", "glu_product", 0),
    "glu_right_slice_to_sigmoid": _edge("glu_right_slice", "glu_sigmoid", 0),
    "glu_sigmoid_to_product": _edge("glu_sigmoid", "glu_product", 1),
}

def _edge_range(first: str, last: str, *, exclude: tuple[str, ...] = ()) -> tuple[str, ...]:
    names = tuple(EDGES)
    selected = names[names.index(first):names.index(last) + 1]
    return tuple(name for name in selected if name not in exclude)

EDGE_GROUPS: dict[str, tuple[str, ...]] = {
    "linear_bias": ("linear_mm_to_bias_add",),
    "linear_transposed": ("linear_weight_transpose_to_mm",),
    "rms_norm": ("rms_square_to_mean", "rms_mean_to_eps_add", "rms_eps_add_to_inv", "rms_inv_to_scale", "rms_scale_to_weight_mul"),
    "rms_norm_pow": ("rms_square_to_mean", "rms_mean_to_eps_add", "rms_eps_add_to_inv_pow", "rms_inv_pow_to_scale", "rms_scale_to_weight_mul"),
    "rms_norm_no_weight": ("rms_square_to_mean", "rms_mean_to_eps_add", "rms_eps_add_to_inv", "rms_inv_to_scale"),
    "rms_norm_pow_no_weight": ("rms_square_to_mean", "rms_mean_to_eps_add", "rms_eps_add_to_inv_pow", "rms_inv_pow_to_scale"),
    "layernorm": _edge_range("ln_mean_to_center", "ln_weight_mul_to_bias_add"),
    "swiglu_mlp": _edge_range("gate_proj_to_activation", "mlp_product_to_down_proj"),
    "gelu_mlp": ("up_proj_to_gelu", "gelu_to_down_proj"),
    "silu_decomposed": ("silu_sigmoid_to_product",),
    "glu_decomposed": _edge_range("glu_left_slice_to_product", "glu_sigmoid_to_product"),
    "gemma4_geglu_mlp": _edge_range("gate_input_view_to_gate_proj", "down_proj_to_down_proj_view"),
    "attention_core": ("attn_qk_to_scale", "attn_scale_to_mask_add", "attn_scale_to_softmax", "attn_mask_add_to_softmax", "attn_softmax_to_value"),
    "lfm_bmm_masked_attention": _edge_range("lfm_attn_query_expand_to_flat", "lfm_attn_output_bmm_to_view"),
    "rope": (
        "rope_slice_odd_to_neg", "rope_neg_to_rotate_cat", "rope_slice_even_to_rotate_cat",
        "rope_rotate_cat_to_sin_mul", "rope_cos_mul_to_add", "rope_sin_mul_to_add",
    ),
    "conv_bias": ("conv_to_bias_add",),
    "short_conv_prefill": ("conv_to_slice",),
    "short_conv_decode": ("multiply_to_sum",),
    "lstm_cell": _edge_range("lstm_gate_mm_to_add", "lstm_add_to_tanh"),
    "lfm_conv_cache_roll_append": _edge_range("lfm_conv_cache_clone_to_output_copy", "lfm_conv_cache_value_slice_last_to_value_copy"),
    "lfm_grouped_moe": _edge_range(
        "moe_hidden_to_router", "moe_output_view_to_combine",
        exclude=("moe_token_expand_to_flat", "moe_gate_copy_to_silu", "moe_gate_silu_to_copy"),
    ),
}

def _without_token_clone(group: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(
        "moe_token_expand_to_flat" if name == "moe_token_expand_to_clone" else name
        for name in group
        if name != "moe_token_clone_to_flat"
    )

EDGE_GROUPS["lfm_grouped_moe_no_token_clone"] = _without_token_clone(EDGE_GROUPS["lfm_grouped_moe"])
EDGE_GROUPS["lfm_grouped_moe_silu"] = tuple(
    name for name in EDGE_GROUPS["lfm_grouped_moe"]
    if name not in {"moe_gate_copy_to_sigmoid", "moe_gate_copy_to_activation", "moe_gate_sigmoid_to_activation", "moe_gate_activation_to_copy"}
) + ("moe_gate_copy_to_silu", "moe_gate_silu_to_copy")
EDGE_GROUPS["lfm_grouped_moe_silu_no_token_clone"] = _without_token_clone(EDGE_GROUPS["lfm_grouped_moe_silu"])
for suffix in ("", "_no_token_clone", "_silu", "_silu_no_token_clone"):
    EDGE_GROUPS[f"lfm_grouped_moe_{'silu_' if 'silu' in suffix else ''}direct_router{'_no_token_clone' if 'no_token_clone' in suffix else ''}"] = tuple(
        name for name in EDGE_GROUPS[f"lfm_grouped_moe{suffix}"]
        if name != "moe_router_weight_to_router"
    )
