from . import models as M

EXPERT_GROUP = "experts"
CACHE_STATE_VALUE_KINDS = (
    M.ValueKind.CACHE_STATE,
    M.ValueKind.CACHE_INPUT,
    M.ValueKind.CACHE_OUTPUT,
)


ATEN_OPS: dict[str, tuple[str, ...]] = {
    "placeholder": ("placeholder",),
    "getitem": ("operator.getitem", "<built-in function getitem>"),
    "embedding": ("aten.embedding.default", "aten.index_select.default", "aten.gather.default"),
    "matmul": ("aten.mm.default", "aten.matmul.default", "aten.bmm.default", "aten.addmm.default", "aten.linear.default", "cactus.matmul"),
    "add": ("aten.add.Tensor", "aten.add.Scalar", "operator.add", "<built-in function add>", "cactus.add", "cactus.scalar_add"),
    "sub": ("aten.sub.Tensor", "aten.sub.Scalar", "operator.sub", "<built-in function sub>", "cactus.subtract", "cactus.scalar_subtract"),
    "mul": ("aten.mul.Tensor", "aten.mul.Scalar", "operator.mul", "<built-in function mul>", "cactus.multiply", "cactus.scalar_multiply"),
    "div": ("aten.div.Tensor", "aten.div.Scalar", "operator.truediv", "<built-in function truediv>", "cactus.divide", "cactus.scalar_divide"),
    "floor_divide": ("aten.floor_divide.default", "aten.div.Tensor_mode"),
    "fmod": ("aten.fmod.Scalar",),
    "abs": ("aten.abs.default",),
    "pow": ("aten.pow.Tensor_Scalar", "aten.pow.Tensor_Tensor", "aten.pow.Scalar"),
    "sqrt": ("aten.sqrt.default", "aten.rsqrt.default"),
    "exp": ("aten.exp.default",),
    "cos": ("aten.cos.default",),
    "sin": ("aten.sin.default",),
    "log": ("aten.log.default",),
    "mean": ("aten.mean.dim", "aten.mean.default"),
    "sum": ("aten.sum.dim_IntList", "aten.sum.default"),
    "var": ("aten.var.dim", "aten.var.correction"),
    "max": ("aten.max.dim", "aten.amax.default"),
    "min": ("aten.min.dim", "aten.amin.default"),
    "softmax": ("aten.softmax.int", "aten._softmax.default", "cactus.softmax"),
    "topk": ("aten.topk.default",),
    "sort": ("aten.sort.default",),
    "view": ("aten.view.default", "aten.reshape.default", "aten.flatten.using_ints", "cactus.view", "cactus.reshape"),
    "unsqueeze": ("aten.unsqueeze.default",),
    "expand": ("aten.expand.default",),
    "transpose": ("aten.t.default", "aten.transpose.int", "aten.permute.default", "cactus.transpose"),
    "split": ("aten.split_with_sizes.default", "aten.chunk.default"),
    "slice": ("aten.slice.Tensor", "aten.narrow.default", "cactus.slice"),
    "index": ("aten.select.int", "aten.index.Tensor", "cactus.index"),
    "gather": ("aten.gather.default", "aten.index_select.default", "cactus.gather"),
    "index_put": ("aten.index_put.default", "cactus.index_put"),
    "cat": ("aten.cat.default", "cactus.cat"),
    "scatter": ("aten.scatter.src", "aten.scatter.value", "aten.scatter_reduce.two"),
    "histc": ("aten.histc.default",),
    "cumsum": ("aten.cumsum.default",),
    "empty": ("aten.empty_permuted.default",),
    "grouped_mm": ("transformers.grouped_mm_fallback.default",),
    "neg": ("aten.neg.default", "operator.neg", "<built-in function neg>"),
    "where": ("aten.where.self",),
    "eq": ("aten.eq.Tensor", "aten.eq.Scalar"),
    "logical_not": ("aten.logical_not.default",),
    "any": ("aten.any.dim",),
    "ne": ("aten.ne.Tensor", "aten.ne.Scalar"),
    "lt": ("aten.lt.Tensor", "aten.lt.Scalar"),
    "gt": ("aten.gt.Tensor", "aten.gt.Scalar"),
    "full": ("aten.full.default", "aten.full_like.default"),
    "arange": ("aten.arange.default", "aten.arange.start", "aten.arange.start_step"),
    "scalar_tensor": ("aten.scalar_tensor.default",),
    "copy": ("aten.clone.default", "aten._to_copy.default", "aten.contiguous.default"),
    "copy_write": ("aten.copy.default",),
    "slice_scatter": ("aten.slice_scatter.default",),
    "relu": ("aten.relu.default",),
    "silu": ("aten.silu.default", "aten.sigmoid.default"),
    "gelu": ("aten.gelu.default",),
    "tanh": ("aten.tanh.default",),
    "sigmoid": ("aten.sigmoid.default",),
    "clamp": ("aten.clamp.default", "aten.clamp.Tensor"),
    "conv": ("aten.convolution.default", "aten.conv1d.default", "aten.conv2d.default"),
    "groupnorm": ("aten.native_group_norm.default", "aten.group_norm.default"),
    "batchnorm": ("aten.native_batch_norm.default", "aten.batch_norm.default"),
    "layernorm": ("aten.native_layer_norm.default", "aten.layer_norm.default"),
    "scaled_dot_product_attention": ("aten.scaled_dot_product_attention.default",),
    "stft": ("aten.stft.default",),
    "fft": ("aten.fft_rfft.default", "aten.fft_irfft.default"),
}


def _attr(
    name: str,
    value: object = None,
    *,
    required: bool = True,
) -> M.AttrConstraint:
    return M.AttrConstraint(name=name, value=value, required=required)


def _node(
    name: str,
    op_key: str,
    *,
    attrs: tuple[M.AttrConstraint, ...] = (),
    repeated: bool = False,
    repeated_group: str | None = None,
    allowed_value_kinds: tuple[str, ...] = (),
    tensor_constraints: tuple[M.TensorConstraint, ...] = (),
    metadata: dict | None = None,
) -> M.FusionNode:
    return M.FusionNode(
        name=name,
        ops=ATEN_OPS[op_key],
        attrs=attrs,
        repeated=repeated,
        repeated_group=repeated_group,
        allowed_value_kinds=allowed_value_kinds,
        tensor_constraints=tensor_constraints,
        metadata=metadata or {},
    )


def _expert_node(name: str, op_key: str) -> M.FusionNode:
    return _node(name, op_key, repeated=True, repeated_group=EXPERT_GROUP)


# def _index_nodes_by_op(nodes: dict[str, M.FusionNode]) -> dict[str, tuple[str, ...]]:
#     index: dict[str, tuple[str, ...]] = {}

#     for node_name, node in nodes.items():
#         for op in node.ops:
#             index[op] = (*index.get(op, ()), node_name)

#     return index


NODES: dict[str, M.FusionNode] = {
    "add": _node("add", "add"),
    "subtract": _node("subtract", "sub"),
    "multiply": _node("multiply", "mul"),
    "divide": _node("divide", "div"),
    "abs": _node("abs", "abs"),
    "pow": _node("pow", "pow"),
    "sqrt": _node("sqrt", "sqrt"),
    "scalar_add": _node("scalar_add", "add"),
    "scalar_subtract": _node("scalar_subtract", "sub"),
    "scalar_multiply": _node("scalar_multiply", "mul"),
    "scalar_divide": _node("scalar_divide", "div"),
    "scalar_floor_divide": _node("scalar_floor_divide", "floor_divide"),
    "scalar_exp": _node("scalar_exp", "exp"),
    "scalar_sqrt": _node("scalar_sqrt", "sqrt"),
    "scalar_cos": _node("scalar_cos", "cos"),
    "scalar_sin": _node("scalar_sin", "sin"),
    "scalar_log": _node("scalar_log", "log"),
    "mean": _node("mean", "mean"),
    "sum": _node("sum", "sum"),
    "variance": _node("variance", "var"),
    "min": _node("min", "min"),
    "max": _node("max", "max"),
    "softmax": _node("softmax", "softmax"),
    "topk_direct": _node("topk_direct", "topk"),
    "sort": _node("sort", "sort"),
    "view": _node("view", "view"),
    "reshape": _node("reshape", "view"),
    "flatten": _node("flatten", "view"),
    "unsqueeze": _node("unsqueeze", "unsqueeze"),
    "expand": _node("expand", "expand"),
    "transpose": _node("transpose", "transpose"),
    "split": _node("split", "split"),
    "slice": _node("slice", "slice"),
    "index": _node("index", "index"),
    "index_put": _node("index_put", "index_put"),
    "cat": _node("cat", "cat"),
    "gather": _node("gather", "gather"),
    "histc": _node("histc", "histc"),
    "cumsum": _node("cumsum", "cumsum"),
    "empty": _node("empty", "empty"),
    "not_equal": _node("not_equal", "ne"),
    "equal": _node("equal", "eq"),
    "embedding": _node("embedding", "embedding"),
    "linear_mm": _node("linear_mm", "matmul"),
    "linear_bias_add": _node("linear_bias_add", "add"),
    "rms_square": _node("rms_square", "pow", attrs=(_attr("exponent", 2, required=False),)),
    "rms_mean": _node("rms_mean", "mean", attrs=(_attr("dim", -1, required=False),)),
    "rms_eps_add": _node("rms_eps_add", "add"),
    "rms_inv": _node("rms_inv", "sqrt"),
    "rms_scale": _node("rms_scale", "mul"),
    "rms_weight_mul": _node("rms_weight_mul", "mul"),
    "ln_mean": _node("ln_mean", "mean", attrs=(_attr("dim", -1, required=False),)),
    "ln_center": _node("ln_center", "sub"),
    "ln_square": _node("ln_square", "pow", attrs=(_attr("exponent", 2, required=False),)),
    "ln_var": _node("ln_var", "mean", attrs=(_attr("dim", -1, required=False),)),
    "ln_eps_add": _node("ln_eps_add", "add"),
    "ln_inv": _node("ln_inv", "sqrt"),
    "ln_norm": _node("ln_norm", "mul"),
    "ln_weight_mul": _node("ln_weight_mul", "mul"),
    "ln_bias_add": _node("ln_bias_add", "add"),
    "groupnorm_mean": _node("groupnorm_mean", "mean"),
    "groupnorm_var": _node("groupnorm_var", "var"),
    "groupnorm": _node("groupnorm", "groupnorm"),
    "batchnorm": _node("batchnorm", "batchnorm"),
    "layernorm_direct": _node("layernorm_direct", "layernorm"),
    "batchnorm_sub_mean": _node("batchnorm_sub_mean", "sub"),
    "batchnorm_div_std": _node("batchnorm_div_std", "div"),
    "relu": _node("relu", "relu"),
    "silu": _node("silu", "silu"),
    "gelu": _node("gelu", "gelu"),
    "gelu_erf": _node("gelu_erf", "gelu", metadata={"approximation": "erf"}),
    "sigmoid": _node("sigmoid", "sigmoid"),
    "tanh": _node("tanh", "tanh"),
    "clamp": _node("clamp", "clamp"),
    "glu": _node("glu", "mul"),
    "gate_proj": _node("gate_proj", "matmul"),
    "up_proj": _node("up_proj", "matmul"),
    "mlp_activation": _node("mlp_activation", "silu"),
    "mlp_product": _node("mlp_product", "mul"),
    "down_proj": _node("down_proj", "matmul"),
    "q_proj": _node("q_proj", "matmul"),
    "k_proj": _node("k_proj", "matmul"),
    "v_proj": _node("v_proj", "matmul"),
    "q_view": _node("q_view", "view"),
    "k_view": _node("k_view", "view"),
    "v_view": _node("v_view", "view"),
    "q_rope": _node("q_rope", "add"),
    "k_rope": _node("k_rope", "add"),
    "attn_qk": _node("attn_qk", "matmul"),
    "attn_scale": _node("attn_scale", "mul"),
    "attn_mask_add": _node("attn_mask_add", "add"),
    "attn_softmax": _node("attn_softmax", "softmax"),
    "attn_value": _node("attn_value", "matmul"),
    "attn_sdp": _node("attn_sdp", "scaled_dot_product_attention"),
    "lfm_attn_query_expand": _node("lfm_attn_query_expand", "expand"),
    "lfm_attn_key_expand": _node("lfm_attn_key_expand", "expand"),
    "lfm_attn_value_expand": _node("lfm_attn_value_expand", "expand"),
    "lfm_attn_query_flat": _node("lfm_attn_query_flat", "view"),
    "lfm_attn_key_flat": _node("lfm_attn_key_flat", "view"),
    "lfm_attn_value_flat": _node("lfm_attn_value_flat", "view"),
    "lfm_attn_qk": _node("lfm_attn_qk", "matmul"),
    "lfm_attn_logits_view": _node("lfm_attn_logits_view", "view"),
    "lfm_attn_mask_where": _node("lfm_attn_mask_where", "where"),
    "lfm_attn_mask_zero": _node("lfm_attn_mask_zero", "scalar_tensor"),
    "lfm_attn_mask_fill": _node("lfm_attn_mask_fill", "scalar_tensor"),
    "lfm_attn_mask_add": _node("lfm_attn_mask_add", "add"),
    "lfm_attn_softmax": _node("lfm_attn_softmax", "softmax"),
    "lfm_attn_null_eq": _node("lfm_attn_null_eq", "eq"),
    "lfm_attn_valid_not": _node("lfm_attn_valid_not", "logical_not"),
    "lfm_attn_any_valid": _node("lfm_attn_any_valid", "any"),
    "lfm_attn_invalid_not": _node("lfm_attn_invalid_not", "logical_not"),
    "lfm_attn_zero_like": _node("lfm_attn_zero_like", "full"),
    "lfm_attn_probs_where": _node("lfm_attn_probs_where", "where"),
    "lfm_attn_probs_expand": _node("lfm_attn_probs_expand", "expand"),
    "lfm_attn_probs_flat": _node("lfm_attn_probs_flat", "view"),
    "lfm_attn_output_bmm": _node("lfm_attn_output_bmm", "matmul"),
    "lfm_attn_output_view": _node("lfm_attn_output_view", "view"),
    "rel_pos_bias": _node("rel_pos_bias", "matmul"),
    "rope_slice_even": _node("rope_slice_even", "slice"),
    "rope_slice_odd": _node("rope_slice_odd", "slice"),
    "rope_neg": _node("rope_neg", "neg"),
    "rope_rotate_cat": _node("rope_rotate_cat", "cat"),
    "rope_cos_mul": _node("rope_cos_mul", "mul"),
    "rope_sin_mul": _node("rope_sin_mul", "mul"),
    "rope_add": _node("rope_add", "add"),
    "conv": _node("conv", "conv"),
    "conv_bias_add": _node("conv_bias_add", "add"),
    "conv_cache_append": _node("conv_cache_append", "cat"),
    "conv_cache_initialize": _node("conv_cache_initialize", "copy"),
    "lfm_conv_cache_clone": _node("lfm_conv_cache_clone", "copy"),
    "lfm_conv_cache_roll_arange": _node("lfm_conv_cache_roll_arange", "arange"),
    "lfm_conv_cache_roll_add": _node("lfm_conv_cache_roll_add", "add"),
    "lfm_conv_cache_roll_mod": _node("lfm_conv_cache_roll_mod", "fmod"),
    "lfm_conv_cache_gather": _node("lfm_conv_cache_gather", "gather"),
    "lfm_conv_cache_scatter_slice_dim0": _node("lfm_conv_cache_scatter_slice_dim0", "slice"),
    "lfm_conv_cache_scatter_slice_dim1": _node("lfm_conv_cache_scatter_slice_dim1", "slice"),
    "lfm_conv_cache_value_slice_dim0": _node("lfm_conv_cache_value_slice_dim0", "slice"),
    "lfm_conv_cache_value_slice_dim1": _node("lfm_conv_cache_value_slice_dim1", "slice"),
    "lfm_conv_cache_value_slice_last": _node("lfm_conv_cache_value_slice_last", "slice"),
    "lfm_conv_cache_value_copy": _node("lfm_conv_cache_value_copy", "copy_write"),
    "lfm_conv_cache_scatter_dim2": _node("lfm_conv_cache_scatter_dim2", "slice_scatter"),
    "lfm_conv_cache_scatter_dim1": _node("lfm_conv_cache_scatter_dim1", "slice_scatter"),
    "lfm_conv_cache_scatter_dim0": _node("lfm_conv_cache_scatter_dim0", "slice_scatter"),
    "lfm_conv_cache_output_copy": _node("lfm_conv_cache_output_copy", "copy_write"),
    "conv_cache_state": _node("conv_cache_state", "placeholder", allowed_value_kinds=CACHE_STATE_VALUE_KINDS),
    "kv_cache_append": _node("kv_cache_append", "cat"),
    "kv_cache_state": _node("kv_cache_state", "placeholder", allowed_value_kinds=CACHE_STATE_VALUE_KINDS),
    "recurrent_cache_state": _node("recurrent_cache_state", "placeholder", allowed_value_kinds=CACHE_STATE_VALUE_KINDS),
    "recurrent_cache_write": _node("recurrent_cache_write", "copy"),
    "lstm_gate_mm": _node("lstm_gate_mm", "matmul"),
    "lstm_recurrent_mm": _node("lstm_recurrent_mm", "matmul"),
    "lstm_gate_add": _node("lstm_gate_add", "add"),
    "lstm_sigmoid": _node("lstm_sigmoid", "sigmoid"),
    "lstm_tanh": _node("lstm_tanh", "tanh"),
    "delta_q": _node("delta_q", "matmul"),
    "delta_k": _node("delta_k", "matmul"),
    "delta_v": _node("delta_v", "matmul"),
    "delta_gate": _node("delta_gate", "matmul"),
    "delta_prefill": _node("delta_prefill", "matmul"),
    "router_logits": _node("router_logits", "matmul"),
    "routing_probs": _node("routing_probs", "softmax"),
    "topk": _node("topk", "topk"),
    "moe_hidden_view": _node("moe_hidden_view", "view"),
    "moe_router_weight_transpose": _node("moe_router_weight_transpose", "transpose"),
    "moe_router_logits": _node("moe_router_logits", "matmul"),
    "moe_router_sigmoid": _node("moe_router_sigmoid", "sigmoid"),
    "moe_router_bias": _node("moe_router_bias", "add"),
    "moe_topk": _node("moe_topk", "topk"),
    "moe_topk_indices": _node("moe_topk_indices", "getitem", attrs=(_attr("index", 1),)),
    "moe_routing_gather": _node("moe_routing_gather", "embedding"),
    "moe_routing_sum": _node("moe_routing_sum", "sum"),
    "moe_routing_eps": _node("moe_routing_eps", "add"),
    "moe_routing_norm": _node("moe_routing_norm", "div"),
    "moe_routing_scale": _node("moe_routing_scale", "mul"),
    "moe_token_arange": _node("moe_token_arange", "arange"),
    "moe_token_unsqueeze": _node("moe_token_unsqueeze", "unsqueeze"),
    "moe_token_expand": _node("moe_token_expand", "expand"),
    "moe_token_clone": _node("moe_token_clone", "copy"),
    "moe_token_flat": _node("moe_token_flat", "view"),
    "moe_routing_flat": _node("moe_routing_flat", "view"),
    "moe_topk_flat": _node("moe_topk_flat", "view"),
    "moe_sort": _node("moe_sort", "sort"),
    "moe_sort_indices": _node("moe_sort_indices", "getitem", attrs=(_attr("index", 1),)),
    "moe_unsort_empty": _node("moe_unsort_empty", "empty"),
    "moe_unsort_arange": _node("moe_unsort_arange", "arange"),
    "moe_unsort_index_put": _node("moe_unsort_index_put", "index_put"),
    "moe_sorted_expert_index": _node("moe_sorted_expert_index", "index"),
    "moe_sorted_expert_copy": _node("moe_sorted_expert_copy", "copy"),
    "moe_histc": _node("moe_histc", "histc"),
    "moe_offsets": _node("moe_offsets", "cumsum"),
    "moe_sorted_routing_index": _node("moe_sorted_routing_index", "index"),
    "moe_token_positions_index": _node("moe_token_positions_index", "index"),
    "moe_sorted_hidden_index": _node("moe_sorted_hidden_index", "index"),
    "moe_gate_up_weight_transpose": _node("moe_gate_up_weight_transpose", "transpose"),
    "moe_grouped_gate_up": _node("moe_grouped_gate_up", "grouped_mm"),
    "moe_gate_up_split": _node("moe_gate_up_split", "split"),
    "moe_gate_tensor": _node("moe_gate_tensor", "getitem", attrs=(_attr("index", 0),)),
    "moe_up_tensor": _node("moe_up_tensor", "getitem", attrs=(_attr("index", 1),)),
    "moe_gate_copy": _node("moe_gate_copy", "copy"),
    "moe_gate_sigmoid": _node("moe_gate_sigmoid", "sigmoid"),
    "moe_gate_activation": _node("moe_gate_activation", "mul"),
    "moe_gate_activation_copy": _node("moe_gate_activation_copy", "copy"),
    "moe_expert_product": _node("moe_expert_product", "mul"),
    "moe_down_weight_transpose": _node("moe_down_weight_transpose", "transpose"),
    "moe_grouped_down": _node("moe_grouped_down", "grouped_mm"),
    "moe_routing_unsqueeze": _node("moe_routing_unsqueeze", "unsqueeze"),
    "moe_grouped_weighted": _node("moe_grouped_weighted", "mul"),
    "moe_unsort_index": _node("moe_unsort_index", "index"),
    "moe_output_view": _node("moe_output_view", "view"),
    "moe_grouped_combine": _node("moe_grouped_combine", "sum"),
    "expert_gate": _expert_node("expert_gate", "matmul"),
    "expert_up": _expert_node("expert_up", "matmul"),
    "expert_activation": _expert_node("expert_activation", "silu"),
    "expert_product": _expert_node("expert_product", "mul"),
    "expert_down": _expert_node("expert_down", "matmul"),
    "expert_weighted": _expert_node("expert_weighted", "mul"),
    "moe_combine": _node("moe_combine", "sum"),
    "rfft": _node("rfft", "fft"),
    "irfft": _node("irfft", "fft"),
    "stft": _node("stft", "stft"),
    "spectrogram": _node("spectrogram", "stft"),
    "image_preprocess": _node("image_preprocess", "view"),
    "bilinear_interpolation": _node("bilinear_interpolation", "view"),
    "sample_topk": _node("sample_topk", "topk"),
    "sample_softmax": _node("sample_softmax", "softmax"),
    "scatter_topk": _node("scatter_topk", "topk"),
    "scatter": _node("scatter", "scatter"),
    "gaussian_topk": _node("gaussian_topk", "topk"),
    "altup_predict": _node("altup_predict", "add"),
    "altup_correct": _node("altup_correct", "add"),
}


# NODE_NAMES_BY_OP: dict[str, tuple[str, ...]] = _index_nodes_by_op(NODES)


NODE_GROUPS: dict[str, tuple[str, ...]] = {
    "direct_tensor": (
        "add",
        "subtract",
        "multiply",
        "divide",
        "abs",
        "pow",
        "sqrt",
        "scalar_add",
        "scalar_subtract",
        "scalar_multiply",
        "scalar_divide",
        "scalar_floor_divide",
        "scalar_exp",
        "scalar_sqrt",
        "scalar_cos",
        "scalar_sin",
        "scalar_log",
        "mean",
        "sum",
        "variance",
        "min",
        "max",
        "softmax",
        "topk_direct",
        "view",
        "reshape",
        "flatten",
        "transpose",
        "slice",
        "index",
        "cat",
        "gather",
        "not_equal",
        "equal",
    ),
    "linear": ("linear_mm", "linear_bias_add"),
    "normalization": (
        "rms_square",
        "rms_mean",
        "rms_eps_add",
        "rms_inv",
        "rms_scale",
        "rms_weight_mul",
        "ln_mean",
        "ln_center",
        "ln_square",
        "ln_var",
        "ln_eps_add",
        "ln_inv",
        "ln_norm",
        "ln_weight_mul",
        "ln_bias_add",
    ),
    "activation": ("relu", "silu", "gelu", "gelu_erf", "sigmoid", "tanh", "clamp", "glu"),
    "mlp": ("gate_proj", "up_proj", "mlp_activation", "mlp_product", "down_proj"),
    "attention": (
        "q_proj",
        "k_proj",
        "v_proj",
        "q_view",
        "k_view",
        "v_view",
        "q_rope",
        "k_rope",
        "attn_qk",
        "attn_scale",
        "attn_mask_add",
        "attn_softmax",
        "attn_value",
        "attn_sdp",
    ),
    "rope": (
        "rope_slice_even",
        "rope_slice_odd",
        "rope_neg",
        "rope_rotate_cat",
        "rope_cos_mul",
        "rope_sin_mul",
        "rope_add",
    ),
    "conv": ("conv", "conv_bias_add", "conv_cache_append"),
    "cache": (
        "kv_cache_state",
        "kv_cache_append",
        "conv_cache_state",
        "conv_cache_append",
        "conv_cache_initialize",
        "lfm_conv_cache_clone",
        "lfm_conv_cache_roll_arange",
        "lfm_conv_cache_roll_add",
        "lfm_conv_cache_roll_mod",
        "lfm_conv_cache_gather",
        "lfm_conv_cache_scatter_slice_dim0",
        "lfm_conv_cache_scatter_slice_dim1",
        "lfm_conv_cache_value_slice_dim0",
        "lfm_conv_cache_value_slice_dim1",
        "lfm_conv_cache_value_slice_last",
        "lfm_conv_cache_value_copy",
        "lfm_conv_cache_scatter_dim2",
        "lfm_conv_cache_scatter_dim1",
        "lfm_conv_cache_scatter_dim0",
        "lfm_conv_cache_output_copy",
        "recurrent_cache_state",
        "recurrent_cache_write",
    ),
    "moe": (
        "router_logits",
        "routing_probs",
        "topk",
        "moe_hidden_view",
        "moe_router_weight_transpose",
        "moe_router_logits",
        "moe_router_sigmoid",
        "moe_router_bias",
        "moe_topk",
        "moe_topk_indices",
        "moe_routing_gather",
        "moe_routing_sum",
        "moe_routing_eps",
        "moe_routing_norm",
        "moe_routing_scale",
        "moe_token_arange",
        "moe_token_unsqueeze",
        "moe_token_expand",
        "moe_token_clone",
        "moe_token_flat",
        "moe_routing_flat",
        "moe_topk_flat",
        "moe_sort",
        "moe_sort_indices",
        "moe_unsort_empty",
        "moe_unsort_arange",
        "moe_unsort_index_put",
        "moe_sorted_expert_index",
        "moe_sorted_expert_copy",
        "moe_histc",
        "moe_offsets",
        "moe_sorted_routing_index",
        "moe_token_positions_index",
        "moe_sorted_hidden_index",
        "moe_gate_up_weight_transpose",
        "moe_grouped_gate_up",
        "moe_gate_up_split",
        "moe_gate_tensor",
        "moe_up_tensor",
        "moe_gate_copy",
        "moe_gate_sigmoid",
        "moe_gate_activation",
        "moe_gate_activation_copy",
        "moe_expert_product",
        "moe_down_weight_transpose",
        "moe_grouped_down",
        "moe_routing_unsqueeze",
        "moe_grouped_weighted",
        "moe_unsort_index",
        "moe_output_view",
        "moe_grouped_combine",
        "expert_gate",
        "expert_up",
        "expert_activation",
        "expert_product",
        "expert_down",
        "expert_weighted",
        "moe_combine",
    ),
}
